language: haskell
before_install:
  # Uncomment the next 3 lines whenever hackage is down.
  #  - mkdir -p ~/.cabal
  #  - cp config ~/.cabal/config
  #  - cabal update

  # Try installing some of the build-deps with apt-get for speed.
  - ./travis-tests
  # - ./travis-benchmarks
  # adding the hunit test suite causes us to have to reinstall regex-posix and regex-base
  - cabal install --only-dependencies --enable-tests --force-reinstall
  # - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstall
install:
  # we have to configure rather than install in order to get benchmarks
  - cabal configure --enable-tests -fdump-splices
  # - cabal configure --enable-tests --enable-benchmarks -fdump-splices
  - cabal build
script:
  - cabal test --show-details=always
  # - cabal bench
notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "%{repository}%{build_number} (%{branch} - %{commit} : %{author}) : %{message}"
      - "Details: %{build_url}, %{compare_url}"
