language: haskell
before_install:
  # Uncomment the next line whenever hackage is down.
  #  - mkdir -p ~/.cabal & cp config ~/.cabal/config & cabal update

  # Try installing some of the build-deps with apt-get for speed.
  - ./travis-cabal-apt-install --only-dependencies --force-reinstall $CABAL_APT
install:
  - cabal configure $CABAL_APT
  - cabal build
script:
  - $GO
notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "lens/%{branch} %{commit} %{author} (%{MODE} #${build_number}): %{message}"
      - "Details: %{build_url}"
env:
  - MODE=test-suite CABAL_APT="--enable-tests" GO="cabal test --show-details=always"
  - MODE=benchmarks CABAL_APT="--enable-benchmarks -fdump-splices" GO="cabal bench"
