language: haskell
before_install:
  # Uncomment the next 3 lines whenever hackage is down.
  #  - mkdir -p ~/.cabal
  #  - cp config ~/.cabal/config
  #  - cabal update

  # Disable fsync et al. Perhaps this will speed up things just a bit.
  - apt-get -q -y install eatmydata

  # Try installing some of the build-deps with apt-get for speed.
  - eatmydata ./travis-before-install

  # adding the hunit test suite causes us to have to reinstall regex-posix and regex-base
  - eatmydata cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstall
install:
  # we have to configure rather than install in order to get benchmarks
  - eatmydata cabal configure --enable-tests --enable-benchmarks -fdump-splices
  - eatmydata cabal build
script:
  - eatmydata cabal test --show-details=always
  - eatmydata cabal bench
notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "%{repository}%{build_number} (%{branch} - %{commit} : %{author}) : %{message}"
      - "Details: %{build_url}, %{compare_url}"
