language: haskell
before_install:
  # Uncomment the next 3 lines whenever hackage is down.
  #  - mkdir -p ~/.cabal
  #  - cp config ~/.cabal/config
  #  - cabal update

  # Try installing some of the build-deps with apt-get for speed.
  - ./travis-cabal-apt-install --only-dependencies --force-reinstall --enable-tests # --enable-benchmarks
install:
  # we have to configure rather than install in order to get benchmarks
  - cabal configure --enable-tests # -fdump-splices --enable-benchmarks

  - cabal build
script:
  - cabal test # --show-details=always
  # - cabal bench
notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "%{repository}%{build_number} (%{branch} - %{commit} : %{author}) : %{message}"
      - "Details: %{build_url}, %{compare_url}"
