language: haskell
# Use this before_install section when hackage is down.
before_install:
  - mkdir -p ~/.cabal
  - cp config ~/.cabal/config
  - cabal update
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
install:
  - cabal configure --enable-tests --enable-benchmarks
  - cabal build
script:
  - cabal test
  - cabal bench
notifications:
  irc: "irc.freenode.org#haskell-lens"
